### ISSUE TITLE
DTLS_STATE_CLOSING may block session slots

### ISSUE THREAD

**Issue by obgm** [eclipse/tinydtls#95] opened 2021-07-02 08:24 UTC
RIOT-OS/RIOT#16422 correctly states that calling `dtls_close()` may result in a session held in state `DTLS_STATE_CLOSING` forever if no alert messages from the peer are received. Reasons for this might be dropped packets or a crashed/gone peer. A viable solution could include triggering cleanup (either through `dtls_reset_peer()` or `dtls_destroy_peer()`) after some timeout.

**Comment by boaks** [comment] 2021-07-03 13:52
[RFC5246 - 7.2.1.  Closure Alerts](https://datatracker.ietf.org/doc/html/rfc5246#section-7.2.1)

> It is not required for the initiator of the close to wait for the responding close_notify alert before
> closing the read side of the connection.

So, yes, that wait in DTLS_STATE_CLOSING may time out.

In my personal opinion, there are no good reason to use a Closure Alerts for DTLS at all.
The most definitions of RFC5246 (e.g. "required") will require to ACK/retransmit the Closure Alerts for RFC6347 in order to ensure, that the other peer received it.

[RFC6347 - 4.2.7.  Alert Messages](https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.7)

> Note that Alert messages are not retransmitted at all

So, the means to ensure, that a "require"  Closure Alerts is received by the other side, are not used.

- truncation attack
- continue to communicate without encrpytion
-  "It is assumed that closing a connection reliably delivers
   pending data before destroying the transport."

Therefore all that hardly applies to DTLS without ack/retransmission, because without them, Closure Alerts are reduced to "may be received".

**Comment by obgm** [comment] 2021-07-05 08:52
I think that closure alerts are still a good thing as an entity can react immediately on receipt of close_notify while it would have to rely on timeouts otherwise. Thus, these one-shot alerts are useful in the best case. The trade-off taken was apparently between stale connections and truncation attacks.

**Comment by boaks** [comment] 2021-07-05 09:17
I guess, the question is the use-pattern.

If DTLS is used in a "time boxed session" way, then the Closure Alerts and new (resumption) handshakes for the next time makes sense. (With resumption, only the association keys could be freed, the master secret is still kept for resumption. So the benefit of saving resources may not be that large.)

If DTLS is used for "mid-term communication" in order to have less state for communication as CoAP may offer, then handshakes are used e.g once a day or week, and encrypted messages are exchanged without a prior handshake. That's mainly a question of the expected communication behavior of the application.

**Comment by mrdeep1** [comment] 2021-07-05 09:22
I likewise think that a closure alert makes sense when an app no longer wants to transmit.  My leaning would be towards if nothing is heard back from the remote end [RFC6348 4.2.4.1](https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.4.1) for RFC6298's maximum timeout of 60 seconds, then drop the association to prevent stale connections.

I am not convinced that we need a closure alert when a re-negotiate handshake is being undertaken.

**Comment by boaks** [comment] 2021-07-05 09:39
That 60s timeout is used during the handshake. It doesn't s apply to application records.
Anyway, sure you my use smaller timeouts for the association/session in order to free resources earlier, but then I would prefer to have this as option. 

You may either execute frequently handshakes even for only a couple of application bytes, or the associations are used for longer. Therefore DTLS CID helps a lot. 

(In Californium the implementation only cleans-up stale associations, when the resources are required for new association. The experience with that is not too bad.)

**Comment by boaks** [comment] 2021-07-05 09:46
> I am not convinced that we need a closure alert when a re-negotiate handshake is being undertaken.

Using closure alert is not (longer) required in order to resume a handshake, not to mix up with re-negotiate handshakes.

[RFC6347](https://datatracker.ietf.org/doc/html/rfc6347#page-21)

Figure 1 : full handshake (using 6 flights, including a key-exchange, maybe with certificates). If that full handshake is execute over an existing association (epoch > 1), then it's called a re-negotiation handshake (at least, in my understanding)

Figure 2 : abbreviated (resumption) handshake (using 3 flights, no key-exchange, no certificates). Execute not encrypted (epoch 0) . Currently not implemented in tinydtls.

**Comment by mrdeep1** [comment] 2021-07-05 11:55
> (In Californium the implementation only cleans-up stale associations, when the resources are required for new association. The experience with that is not too bad.)

The only caution here is that one needs to be careful about what is stale - immediately after sending the closure alert, or after a time when there there is no response etc.

**Comment by boaks** [comment] 2021-07-05 13:07
The close removes the association but keep the session.
Always the last recently used session is removed, if that gets required for new sessions.
Sending or receiving (successfully pass the MAC filter) will renew the recently used.
Additionally there is a "stale connection threshold", which protects recently used sessions from being removed for new ones.

My intention to mention that was to give some insides in different ideas without too frequent handshakes.

**Comment by boaks** [comment] 2021-07-06 07:24
Just to mention:

Sometimes "close" is used to overcome failures in [RFC6347 - 4.2.8.  Establishing New Associations with Existing Parameters](https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.8). 

So, FMPOV, sure, close should not cause additional trouble, but it's also no solution for broken 4.2.8.
Therefore PR #89. Without that, a new CLIENT:HELLO of epoch 0 gets filter by: 

> Jul 06 09:22:06.622 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:49790 (if1) DTLS: received 84 bytes
> Jul 06 09:22:06 DEBG dtls_handle_message: FOUND PEER
> Jul 06 09:22:06 DEBG got 'handshake' epoch 0 sequence 0 (84 bytes)
> Jul 06 09:22:06 ALRT No security context for epoch: 0
> Jul 06 09:22:06 INFO decrypt_verify() failed, drop message.

[second_hs.pcapng.gz](https://github.com/eclipse/tinydtls/files/6768087/second_hs.pcapng.gz)

**Comment by boaks** [comment] 2021-07-06 08:42
> truncation attacks.

I'm still very confused about the term and UDP. 
e.g. [Wiki](https://en.wikipedia.org/wiki/Transport_Layer_Security)

> SSL 2.0 used the TCP connection close to indicate the end of data. This meant that truncation attacks were possible: the attacker simply forges a TCP FIN, leaving the recipient unaware of an illegitimate end of data message (SSL 3.0 fixed this problem by having an explicit closure alert).

There is just nothing as a TCP FIN for UDP. So, any references, what that attack means for UDP?

**Comment by boaks** [comment] 2021-07-06 08:55
[Truncating TLS Connections to Violate Beliefs in Web Applications](https://www.usenix.org/system/files/conference/woot13/woot13-smyth.pdf)

> Suppose a user initiates a wire transfer to Charlie’s Angels using the following
> 
> HTTP request:POST /wire_transfer.php 
> HTTP/1.1Host: mybank.com
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 40
> amount=1000&recipient=Charlie%27s_Angels
> 
> Further  suppose  that  the  request  is  fragmented  by  TLS
> as follows:  “POST [...]  recipient=Charlie” and“%27sAngels”.  In this setting, an adversary can make a transfer to Charlie,  rather than the intended recipient, simply  by  dropping  the second  (and  crucially  the  last) fragment (e.g., by closing the underlying TCP connection after  the  first  fragment  is  delivered).
> 

All that, makes no sense for UDP / DTLS. Any packet may be dropped, the close doesn't imply, that "all previous" are processed. In my opinion, that must be clearly handled in layers above (e.g. coap blockwise with clear indication, when it's ready).

**Comment by mrdeep1** [comment] 2021-07-06 09:09
The server has started to send Charlie in packet A followed by Angels in packet B.  Client sees packet A, knows that it is getting a response and sends close alert as it will no longer be transmitting.  Client may update Charlie with information rather than update Charlie+Angels if client does not wait for B and server's close alert signalling end of response.

A higher layer has to assume that data is presented in a contiguous fashion and any error recovery is handled by a lower layer.  In the case of CoAP Block-Wise block arrival is lock stepped in than block N+1 can only arrive after the arrival of block N which then requests block N+1.

**Comment by boaks** [comment] 2021-07-06 09:32
I try to understand, but failed ...

```
server                                client
package a       ------->
                         <-------      close
package b      -------->
```

> Client may update Charlie with information rather than update Charlie+Angels if client does not wait for B and server's close alert signalling end of response.

I don't get that. May be you can try to express that in package sequences as above.

> A higher layer has to assume that data is presented in a contiguous fashion and any error recovery is handled by a lower layer. In the case of CoAP Block-Wise block arrival is lock stepped in than block N+1 can only arrive after the arrival of block N which then requests block N+1.

I don't understand the attack. Does the client accept a "message" only contain package a? 
That isn't the case for blockwise, or?

I'm mixed up ...

Truncation will only work, if the upper layer doesn't protect from that.
But I can't see, that a close can help in anyway. if the close is record seqn is n, there is no way to ensure, that record n-1 gets dropped, with or without close. 

In TCP, the messages leaving that layer are ordered and complete (and retransmittted, if not). With that, receiving the close over tpc ensures, that all previous tcp-data is received (that are the tcp grants).

And in UDP there are no such grants. That must be implemented in layers above.
And my conclusion is therefore:
"close" can't prevent from truncation attacks, but an upper layer must.

**Comment by boaks** [comment] 2021-07-06 09:49
Let me try to precise the issue:
It's not about that something may be truncated. For me that is common in UDP and must be mitigated in layers above.
It's about that a close protects from such truncations. And that's in my opinion not true for UDP.

**Comment by mrdeep1** [comment] 2021-07-06 11:18
````
server                                  client
package a         ------->
package b      --- (not yet arrived)
                         <-------      close (no more writing, still can read)
package b(arrives) ---->
close                 ------->     client knows a + b arrived and can process both.
````
and so it is not sending the close_notify that causes the potential truncation, but it is not seeing peer's close_notify that can potentially cause the truncation.  The close means no more writing, but still can read.

RFC5346 7.2.1 (which still holds true for UDP in my opinion as RFC6347 (This document introduces a new version of DTLS, DTLS 1.2, which is defined as a series of deltas to TLS 1.2) is based on RFC5346)
````
   The client and the server must share knowledge that the connection is
   ending in order to avoid a truncation attack.  Either party may
   initiate the exchange of closing messages.
````

So, close_notify transmitted by both peers reduces the chance of a truncation attack, but does not completely eliminate it as the close_notify may get lost and is not allowed to be repeated.

CoAP Block-Wise recommends the use of CON to recover from potential packet loss.  If a close_notify has been recieved, then the CoAP layer should know there is an issue (and report this to the higher layers) and that re-requesting a missing block of data will fail as the remote end has indicated that it will no longer write anything back.

I agree that UDP (and hence DTLS apart any handshake recovery) has no recovery for lost packets and the packets can arrive in any order.  Whatever protocol is using DTLS needs to recover as appropriate when loss / re-ordering before presnting data to a higher layer - sorry if my previous response was a bit confusing here.

**Comment by boaks** [comment] 2021-07-06 11:27
Sorry, my feeling is still: This TCP stuff doesn't apply to UDP.

TCP has grants, the close-protection is based on. 
But these are not the grants og UDP, neither the order nor the completeness. 

Apply a message reorder (UDP only):

```
server                                  client
package a         ------->
package b      --- (not yet arrived)
                         <-------      close (no more writing, still can read)
close                 ------->     client knows a arrived and can process. BAD BAD BAD
package b(arrives) ---->
```

Apply a message drop (UDP only):

```
server                                  client
package a         ------->
package b      --- (not yet arrived)
                         <-------      close (no more writing, still can read)
package b(dropped) --??
close                 ------->     client knows a arrived and can process. BAD BAD BAD
```

It's not about "happy path", it's about UDP and the weaker grants, which makes the trouble.

**Comment by boaks** [comment] 2021-07-06 14:35
I wrote a [e-mail to the tls-mailing list](https://mailarchive.ietf.org/arch/msg/tls/kH2_0vqS_lZgbQfhFtrNARyK6BI/).
Maybe that brings some more light.

**Comment by boaks** [comment] 2021-12-08 16:14
Unfortunately, asking the tls list doesn't enlighten the topic.

One approach to fix the original topic (even without a conclusion, if the justification for using a close includes protection against truncation attacks or not),  would be to start a timer to wait for  receiving the alert answer and on timeout, just "simulate" that reception. 

(What stayed open for me, is the intended behavior of libcoap in that period waiting for the response or timeout.)

**Comment by boaks** [comment] 2022-08-09 06:18
That's fixed. What my be left to discus is the behavior of upper layers, when closing is requested from the other peer. Including, if that requires then also to stay with a possible DTLS role exchange.

**Closed by boaks** 2022-08-09 06:18 UTC
Labels: please close
